include:
  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart
    artifact-name: corne_left_studio
  - board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_view
    artifact-name: corne_right
