# build.yaml - Definieert de hardware configuratie voor je Corne
---
include:
  # Linker helft van de Corne
  - board: nice_nano_v2                    # nice!nano v2 controller
    shield: corne_left nice_view_adapter nice_view   # Corne PCB + nice!view adapter + display
  
  # Rechter helft van de Corne  
  - board: nice_nano_v2                    # nice!nano v2 controller
    shield: corne_right nice_view_adapter nice_view  # Corne PCB + nice!view adapter + display
